// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkypczaviorcphzorvxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpreXBjemF2aW9yY3Boem9ydnh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDQyMjksImV4cCI6MjA2ODUyMDIyOX0.jJNWDrYGGhTQjlgnAZPwh92d4Y431fchmTHzNJTV_FI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});